# Generated by Django 5.2.7 on 2025-11-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobile_banners/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Баннер (мобильный)',
                'verbose_name_plural': 'Баннеры (мобильные)',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер (десктоп)', 'verbose_name_plural': 'Баннеры (десктоп)'},
        ),
    ]
