# Generated by Django 5.2 on 2025-11-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mobilebanner_alter_banner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь потолка (м²)')),
                ('corners', models.IntegerField(verbose_name='Количество углов')),
                ('lights', models.IntegerField(verbose_name='Количество светильников')),
                ('pipes', models.IntegerField(verbose_name='Количество труб')),
                ('ceiling_type', models.CharField(max_length=255, verbose_name='Тип потолка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
