# Generated by Django 5.2.7 on 2025-11-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_callbackrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='dekstop_banners/', verbose_name='Картинка'),
        ),
    ]
