# Generated by Django 5.2.7 on 2025-11-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь потолка (м²)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ceiling_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип потолка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='corners',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество углов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lights',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество светильников'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pipes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество труб'),
        ),
    ]
