# Название нашего workflow для отображения в интерфейсе GitHub
name: Deploy to VPS

# Указываем когда запускать - при push в main ветку
on:
  push:
    branches: [ main ]

# Определяем задачи для выполнения 
jobs:
  deploy:
    # Указываем на какой ОС запускать
    runs-on: ubuntu-latest

    steps:
      # Получаем код из репозитория
      - uses: actions/checkout@v3

      # Деплоим на сервер через SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # Используем секреты из GitHub для подключения
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          # Команды выполняемые на сервере
          script: |
            # Переходим в директорию проекта
            cd /home/x/your_stretch

            # Останавливаем службу приложения  (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop gunicorn_your_stretch

            # Обновляем код из репозитория (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | git pull

            # Если у вас PIP
            # Активируем виртуальное окружение
            # source venv/bin/activate

            # Обновляем зависимости
            # pip install -r requirements.txt

            # Если у вас Poetry (Можно определить путь до poetry which poetry)
            /home/x/.local/bin/poetry install --no-root 

            # Миграции
            /home/x/.local/bin/poetry run python manage.py migrate

            # Создаем файл .env из секрета где записано все его содержимое
            echo "${{ secrets.ENV_FILE }}" > .env

            # Собираем статику 
            /home/v/.local/bin/poetry run python manage.py collectstatic --noinput

            # Перезапускаем systemd сервис (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl start gunicorn_your_stretch

            # Создаем директории, если их нет.
            # Ключ -p позволяет создавать родительские директории, если они отсутствуют, и не выдавать ошибку, если директория уже существует.
            mkdir -p /home/x/your_stretch/staticfiles 
            mkdir -p /home/x/your_stretch/media

            # Устанавливаем права доступа к директориям
            # Для статических файлов: 755 означает, что владелец имеет полные права (чтение, запись, выполнение),
            # а группа и остальные пользователи имеют права на чтение и выполнение. Это безопасно, так как статика только раздается.
            chmod 755 /home/x/your_stretch/staticfiles
            # Для медиафайлов: 775 означает, что владелец и группа имеют полные права (чтение, запись, выполнение),
            # а остальные пользователи имеют права на чтение и выполнение. Это необходимо, так как приложение (через Gunicorn)
            # может загружать файлы в эту директорию, и Nginx должен иметь к ним доступ.
            chmod 775 /home/x/your_stretch/media

            # Устанавливаем владельца и группу для директорий
            # x:www-data означает, что владельцем директории будет пользователь 'x', а группой — 'www-data'.
            # Это критично, поскольку Nginx часто работает под пользователем 'www-data' или входит в эту группу.
            # Таким образом, Nginx сможет читать файлы из этих директорий.
            sudo chown -R x:www-data /home/x/your_stretch/staticfiles
            sudo chown -R x:www-data /home/x/your_stretch/media
